name: Create release on tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Build Docker image
      - run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
      - run: docker buildx create --use
      - run: |
          cat << EOF > Dockerfile
          FROM alpine:latest
          CMD ["echo", "Hello, Simple Docker Image!"]
          EOF
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ vars.REGISTRY_NAMESPACE }}/test-image:${{ env.VERSION }} \
            --push .